//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S5
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://s5.is/SolutionWebService", ConfigurationName="S5.ServiceSoap")]
    public interface ServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://s5.is/SolutionWebService/CreateAbending", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<S5.CreateAbendingResponse> CreateAbendingAsync(S5.CreateAbendingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://s5.is/SolutionWebService/CreateAndUpdateAbending", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<S5.CreateAndUpdateAbendingResponse> CreateAndUpdateAbendingAsync(S5.CreateAndUpdateAbendingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://s5.is/SolutionWebService/CreateAndUpdateAbending_P", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<S5.CreateAndUpdateAbending_PResponse> CreateAndUpdateAbending_PAsync(S5.CreateAndUpdateAbending_PRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://s5.is/SolutionWebService/CreateAndUpdateAbending_A", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<S5.CreateAndUpdateAbending_AResponse> CreateAndUpdateAbending_AAsync(S5.CreateAndUpdateAbending_ARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://s5.is/SolutionWebService/UpdateAbending", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<S5.UpdateAbendingResponse> UpdateAbendingAsync(S5.UpdateAbendingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://s5.is/SolutionWebService/UpdateAbending_P", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<S5.UpdateAbending_PResponse> UpdateAbending_PAsync(S5.UpdateAbending_PRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://s5.is/SolutionWebService/UpdateAbending_A", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<S5.UpdateAbending_AResponse> UpdateAbending_AAsync(S5.UpdateAbending_ARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://s5.is/SolutionWebService/DeleteAbending", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<S5.DeleteAbendingResponse> DeleteAbendingAsync(S5.DeleteAbendingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://s5.is/SolutionWebService/GetAbending", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<S5.GetAbendingResponse> GetAbendingAsync(S5.GetAbendingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://s5.is/SolutionWebService/GetAbending_A", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<S5.GetAbending_AResponse> GetAbending_AAsync(S5.GetAbending_ARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://s5.is/SolutionWebService/GetViewAbendingar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<S5.GetViewAbendingarResponse> GetViewAbendingarAsync(S5.GetViewAbendingarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://s5.is/SolutionWebService/AddFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<S5.AddFileResponse> AddFileAsync(S5.AddFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://s5.is/SolutionWebService/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<S5.HelloWorldResponse> HelloWorldAsync(S5.HelloWorldRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s5.is/SolutionWebService")]
    public partial class ReturnValueABE
    {
        
        private string messageField;
        
        private string detailField;
        
        private ValuesABE valuesField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ValuesABE values
        {
            get
            {
                return this.valuesField;
            }
            set
            {
                this.valuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s5.is/SolutionWebService")]
    public partial class ValuesABE
    {
        
        private string s5RequestIDField;
        
        private string abendingField;
        
        private string kennitalaField;
        
        private string abendingaradiliField;
        
        private string netfangField;
        
        private string simiField;
        
        private string heimilisfangField;
        
        private string lysingField;
        
        private string hnit_AField;
        
        private string hnit_NField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string S5RequestID
        {
            get
            {
                return this.s5RequestIDField;
            }
            set
            {
                this.s5RequestIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Abending
        {
            get
            {
                return this.abendingField;
            }
            set
            {
                this.abendingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Kennitala
        {
            get
            {
                return this.kennitalaField;
            }
            set
            {
                this.kennitalaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Abendingaradili
        {
            get
            {
                return this.abendingaradiliField;
            }
            set
            {
                this.abendingaradiliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Netfang
        {
            get
            {
                return this.netfangField;
            }
            set
            {
                this.netfangField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Simi
        {
            get
            {
                return this.simiField;
            }
            set
            {
                this.simiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Heimilisfang
        {
            get
            {
                return this.heimilisfangField;
            }
            set
            {
                this.heimilisfangField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Lysing
        {
            get
            {
                return this.lysingField;
            }
            set
            {
                this.lysingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Hnit_A
        {
            get
            {
                return this.hnit_AField;
            }
            set
            {
                this.hnit_AField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Hnit_N
        {
            get
            {
                return this.hnit_NField;
            }
            set
            {
                this.hnit_NField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s5.is/SolutionWebService")]
    public partial class ReturnValueAddFile
    {
        
        private string messageField;
        
        private string detailField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://s5.is/SolutionWebService")]
    public partial class ReturnValueView
    {
        
        private string messageField;
        
        private string detailField;
        
        private ReturnValueViewTable tableField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ReturnValueViewTable table
        {
            get
            {
                return this.tableField;
            }
            set
            {
                this.tableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://s5.is/SolutionWebService")]
    public partial class ReturnValueViewTable
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAbending", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class CreateAbendingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public string S5Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=1)]
        public string S5Password;
        
        public CreateAbendingRequest()
        {
        }
        
        public CreateAbendingRequest(string S5Username, string S5Password)
        {
            this.S5Username = S5Username;
            this.S5Password = S5Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAbendingResponse", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class CreateAbendingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public S5.ReturnValueABE CreateAbendingResult;
        
        public CreateAbendingResponse()
        {
        }
        
        public CreateAbendingResponse(S5.ReturnValueABE CreateAbendingResult)
        {
            this.CreateAbendingResult = CreateAbendingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAndUpdateAbending", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class CreateAndUpdateAbendingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public string S5Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=1)]
        public string S5Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=2)]
        public S5.ValuesABE values;
        
        public CreateAndUpdateAbendingRequest()
        {
        }
        
        public CreateAndUpdateAbendingRequest(string S5Username, string S5Password, S5.ValuesABE values)
        {
            this.S5Username = S5Username;
            this.S5Password = S5Password;
            this.values = values;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAndUpdateAbendingResponse", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class CreateAndUpdateAbendingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public S5.ReturnValueABE CreateAndUpdateAbendingResult;
        
        public CreateAndUpdateAbendingResponse()
        {
        }
        
        public CreateAndUpdateAbendingResponse(S5.ReturnValueABE CreateAndUpdateAbendingResult)
        {
            this.CreateAndUpdateAbendingResult = CreateAndUpdateAbendingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAndUpdateAbending_P", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class CreateAndUpdateAbending_PRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public string S5Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=1)]
        public string S5Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=2)]
        public string Abending;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=3)]
        public string Kennitala;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=4)]
        public string Abendingaradili;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=5)]
        public string Netfang;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=6)]
        public string Simi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=7)]
        public string Heimilisfang;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=8)]
        public string Lysing;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=9)]
        public string Hnit_A;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=10)]
        public string Hnit_N;
        
        public CreateAndUpdateAbending_PRequest()
        {
        }
        
        public CreateAndUpdateAbending_PRequest(string S5Username, string S5Password, string Abending, string Kennitala, string Abendingaradili, string Netfang, string Simi, string Heimilisfang, string Lysing, string Hnit_A, string Hnit_N)
        {
            this.S5Username = S5Username;
            this.S5Password = S5Password;
            this.Abending = Abending;
            this.Kennitala = Kennitala;
            this.Abendingaradili = Abendingaradili;
            this.Netfang = Netfang;
            this.Simi = Simi;
            this.Heimilisfang = Heimilisfang;
            this.Lysing = Lysing;
            this.Hnit_A = Hnit_A;
            this.Hnit_N = Hnit_N;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAndUpdateAbending_PResponse", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class CreateAndUpdateAbending_PResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public S5.ReturnValueABE CreateAndUpdateAbending_PResult;
        
        public CreateAndUpdateAbending_PResponse()
        {
        }
        
        public CreateAndUpdateAbending_PResponse(S5.ReturnValueABE CreateAndUpdateAbending_PResult)
        {
            this.CreateAndUpdateAbending_PResult = CreateAndUpdateAbending_PResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAndUpdateAbending_A", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class CreateAndUpdateAbending_ARequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public string S5Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=1)]
        public string S5Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=2)]
        public S5.ValuesABE[] cards;
        
        public CreateAndUpdateAbending_ARequest()
        {
        }
        
        public CreateAndUpdateAbending_ARequest(string S5Username, string S5Password, S5.ValuesABE[] cards)
        {
            this.S5Username = S5Username;
            this.S5Password = S5Password;
            this.cards = cards;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAndUpdateAbending_AResponse", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class CreateAndUpdateAbending_AResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public S5.ReturnValueABE[] CreateAndUpdateAbending_AResult;
        
        public CreateAndUpdateAbending_AResponse()
        {
        }
        
        public CreateAndUpdateAbending_AResponse(S5.ReturnValueABE[] CreateAndUpdateAbending_AResult)
        {
            this.CreateAndUpdateAbending_AResult = CreateAndUpdateAbending_AResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateAbending", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class UpdateAbendingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public string S5Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=1)]
        public string S5Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=2)]
        public S5.ValuesABE values;
        
        public UpdateAbendingRequest()
        {
        }
        
        public UpdateAbendingRequest(string S5Username, string S5Password, S5.ValuesABE values)
        {
            this.S5Username = S5Username;
            this.S5Password = S5Password;
            this.values = values;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateAbendingResponse", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class UpdateAbendingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public S5.ReturnValueABE UpdateAbendingResult;
        
        public UpdateAbendingResponse()
        {
        }
        
        public UpdateAbendingResponse(S5.ReturnValueABE UpdateAbendingResult)
        {
            this.UpdateAbendingResult = UpdateAbendingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateAbending_P", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class UpdateAbending_PRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public string S5RequestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=1)]
        public string S5Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=2)]
        public string S5Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=3)]
        public string Abending;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=4)]
        public string Kennitala;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=5)]
        public string Abendingaradili;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=6)]
        public string Netfang;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=7)]
        public string Simi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=8)]
        public string Heimilisfang;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=9)]
        public string Lysing;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=10)]
        public string Hnit_A;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=11)]
        public string Hnit_N;
        
        public UpdateAbending_PRequest()
        {
        }
        
        public UpdateAbending_PRequest(string S5RequestID, string S5Username, string S5Password, string Abending, string Kennitala, string Abendingaradili, string Netfang, string Simi, string Heimilisfang, string Lysing, string Hnit_A, string Hnit_N)
        {
            this.S5RequestID = S5RequestID;
            this.S5Username = S5Username;
            this.S5Password = S5Password;
            this.Abending = Abending;
            this.Kennitala = Kennitala;
            this.Abendingaradili = Abendingaradili;
            this.Netfang = Netfang;
            this.Simi = Simi;
            this.Heimilisfang = Heimilisfang;
            this.Lysing = Lysing;
            this.Hnit_A = Hnit_A;
            this.Hnit_N = Hnit_N;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateAbending_PResponse", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class UpdateAbending_PResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public S5.ReturnValueABE UpdateAbending_PResult;
        
        public UpdateAbending_PResponse()
        {
        }
        
        public UpdateAbending_PResponse(S5.ReturnValueABE UpdateAbending_PResult)
        {
            this.UpdateAbending_PResult = UpdateAbending_PResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateAbending_A", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class UpdateAbending_ARequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public string S5Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=1)]
        public string S5Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=2)]
        public S5.ValuesABE[] cards;
        
        public UpdateAbending_ARequest()
        {
        }
        
        public UpdateAbending_ARequest(string S5Username, string S5Password, S5.ValuesABE[] cards)
        {
            this.S5Username = S5Username;
            this.S5Password = S5Password;
            this.cards = cards;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateAbending_AResponse", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class UpdateAbending_AResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public S5.ReturnValueABE[] UpdateAbending_AResult;
        
        public UpdateAbending_AResponse()
        {
        }
        
        public UpdateAbending_AResponse(S5.ReturnValueABE[] UpdateAbending_AResult)
        {
            this.UpdateAbending_AResult = UpdateAbending_AResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteAbending", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class DeleteAbendingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public string S5RequestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=1)]
        public string S5Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=2)]
        public string S5Password;
        
        public DeleteAbendingRequest()
        {
        }
        
        public DeleteAbendingRequest(string S5RequestID, string S5Username, string S5Password)
        {
            this.S5RequestID = S5RequestID;
            this.S5Username = S5Username;
            this.S5Password = S5Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteAbendingResponse", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class DeleteAbendingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public S5.ReturnValueABE DeleteAbendingResult;
        
        public DeleteAbendingResponse()
        {
        }
        
        public DeleteAbendingResponse(S5.ReturnValueABE DeleteAbendingResult)
        {
            this.DeleteAbendingResult = DeleteAbendingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAbending", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class GetAbendingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public string S5RequestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=1)]
        public string S5Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=2)]
        public string S5Password;
        
        public GetAbendingRequest()
        {
        }
        
        public GetAbendingRequest(string S5RequestID, string S5Username, string S5Password)
        {
            this.S5RequestID = S5RequestID;
            this.S5Username = S5Username;
            this.S5Password = S5Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAbendingResponse", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class GetAbendingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public S5.ReturnValueABE GetAbendingResult;
        
        public GetAbendingResponse()
        {
        }
        
        public GetAbendingResponse(S5.ReturnValueABE GetAbendingResult)
        {
            this.GetAbendingResult = GetAbendingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAbending_A", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class GetAbending_ARequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public string[] S5RequestIDs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=1)]
        public string S5Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=2)]
        public string S5Password;
        
        public GetAbending_ARequest()
        {
        }
        
        public GetAbending_ARequest(string[] S5RequestIDs, string S5Username, string S5Password)
        {
            this.S5RequestIDs = S5RequestIDs;
            this.S5Username = S5Username;
            this.S5Password = S5Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAbending_AResponse", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class GetAbending_AResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public S5.ReturnValueABE[] GetAbending_AResult;
        
        public GetAbending_AResponse()
        {
        }
        
        public GetAbending_AResponse(S5.ReturnValueABE[] GetAbending_AResult)
        {
            this.GetAbending_AResult = GetAbending_AResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetViewAbendingar", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class GetViewAbendingarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public int SortColumn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=1)]
        public bool SortAscending;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=2)]
        public string S5Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=3)]
        public string S5Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=4)]
        public string Kennitala;
        
        public GetViewAbendingarRequest()
        {
        }
        
        public GetViewAbendingarRequest(int SortColumn, bool SortAscending, string S5Username, string S5Password, string Kennitala)
        {
            this.SortColumn = SortColumn;
            this.SortAscending = SortAscending;
            this.S5Username = S5Username;
            this.S5Password = S5Password;
            this.Kennitala = Kennitala;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetViewAbendingarResponse", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class GetViewAbendingarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public S5.ReturnValueView GetViewAbendingarResult;
        
        public GetViewAbendingarResponse()
        {
        }
        
        public GetViewAbendingarResponse(S5.ReturnValueView GetViewAbendingarResult)
        {
            this.GetViewAbendingarResult = GetViewAbendingarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddFile", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class AddFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public string S5RequestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=1)]
        public string S5Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=2)]
        public string S5Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] File;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=4)]
        public string Filename;
        
        public AddFileRequest()
        {
        }
        
        public AddFileRequest(string S5RequestID, string S5Username, string S5Password, byte[] File, string Filename)
        {
            this.S5RequestID = S5RequestID;
            this.S5Username = S5Username;
            this.S5Password = S5Password;
            this.File = File;
            this.Filename = Filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddFileResponse", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class AddFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public S5.ReturnValueAddFile AddFileResult;
        
        public AddFileResponse()
        {
        }
        
        public AddFileResponse(S5.ReturnValueAddFile AddFileResult)
        {
            this.AddFileResult = AddFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorld", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class HelloWorldRequest
    {
        
        public HelloWorldRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorldResponse", WrapperNamespace="http://s5.is/SolutionWebService", IsWrapped=true)]
    public partial class HelloWorldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://s5.is/SolutionWebService", Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponse()
        {
        }
        
        public HelloWorldResponse(string HelloWorldResult)
        {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ServiceSoapChannel : S5.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<S5.ServiceSoap>, S5.ServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<S5.CreateAbendingResponse> CreateAbendingAsync(S5.CreateAbendingRequest request)
        {
            return base.Channel.CreateAbendingAsync(request);
        }
        
        public System.Threading.Tasks.Task<S5.CreateAndUpdateAbendingResponse> CreateAndUpdateAbendingAsync(S5.CreateAndUpdateAbendingRequest request)
        {
            return base.Channel.CreateAndUpdateAbendingAsync(request);
        }
        
        public System.Threading.Tasks.Task<S5.CreateAndUpdateAbending_PResponse> CreateAndUpdateAbending_PAsync(S5.CreateAndUpdateAbending_PRequest request)
        {
            return base.Channel.CreateAndUpdateAbending_PAsync(request);
        }
        
        public System.Threading.Tasks.Task<S5.CreateAndUpdateAbending_AResponse> CreateAndUpdateAbending_AAsync(S5.CreateAndUpdateAbending_ARequest request)
        {
            return base.Channel.CreateAndUpdateAbending_AAsync(request);
        }
        
        public System.Threading.Tasks.Task<S5.UpdateAbendingResponse> UpdateAbendingAsync(S5.UpdateAbendingRequest request)
        {
            return base.Channel.UpdateAbendingAsync(request);
        }
        
        public System.Threading.Tasks.Task<S5.UpdateAbending_PResponse> UpdateAbending_PAsync(S5.UpdateAbending_PRequest request)
        {
            return base.Channel.UpdateAbending_PAsync(request);
        }
        
        public System.Threading.Tasks.Task<S5.UpdateAbending_AResponse> UpdateAbending_AAsync(S5.UpdateAbending_ARequest request)
        {
            return base.Channel.UpdateAbending_AAsync(request);
        }
        
        public System.Threading.Tasks.Task<S5.DeleteAbendingResponse> DeleteAbendingAsync(S5.DeleteAbendingRequest request)
        {
            return base.Channel.DeleteAbendingAsync(request);
        }
        
        public System.Threading.Tasks.Task<S5.GetAbendingResponse> GetAbendingAsync(S5.GetAbendingRequest request)
        {
            return base.Channel.GetAbendingAsync(request);
        }
        
        public System.Threading.Tasks.Task<S5.GetAbending_AResponse> GetAbending_AAsync(S5.GetAbending_ARequest request)
        {
            return base.Channel.GetAbending_AAsync(request);
        }
        
        public System.Threading.Tasks.Task<S5.GetViewAbendingarResponse> GetViewAbendingarAsync(S5.GetViewAbendingarRequest request)
        {
            return base.Channel.GetViewAbendingarAsync(request);
        }
        
        public System.Threading.Tasks.Task<S5.AddFileResponse> AddFileAsync(S5.AddFileRequest request)
        {
            return base.Channel.AddFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<S5.HelloWorldResponse> HelloWorldAsync(S5.HelloWorldRequest request)
        {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://gaedakerfi.kopavogur.is/abendingarws/service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://gaedakerfi.kopavogur.is/abendingarws/service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }
}
